//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string ScheduleID { get; set; }
        public Nullable<System.DateTime> ScheduleDay { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string PeriodTime { get; set; }
        public string TypeOfSchedule { get; set; }
    }
}
